from PyQt5 import QtCore, QtWidgets


class SettingsWindow(QtWidgets.QDialog):
    def __init__(self):
        QtWidgets.QDialog.__init__(self)
        self.resize(252, 350)
        self.setModal(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(self)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.namesButton = QtWidgets.QPushButton(self)
        self.namesButton.setObjectName("namesButton")
        self.gridLayout_4.addWidget(self.namesButton, 3, 0, 1, 1)
        self.okayButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okayButton.sizePolicy().hasHeightForWidth())
        self.okayButton.setSizePolicy(sizePolicy)
        self.okayButton.setObjectName("okayButton")
        self.gridLayout_4.addWidget(self.okayButton, 4, 2, 1, 1)
        self.defaultButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultButton.sizePolicy().hasHeightForWidth())
        self.defaultButton.setSizePolicy(sizePolicy)
        self.defaultButton.setObjectName("defaultButton")
        self.gridLayout_4.addWidget(self.defaultButton, 4, 0, 1, 1)
        self.clipSettingsBox = QtWidgets.QGroupBox(self)
        self.clipSettingsBox.setObjectName("clipSettingsBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.clipSettingsBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clipLength = QtWidgets.QSpinBox(self.clipSettingsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clipLength.sizePolicy().hasHeightForWidth())
        self.clipLength.setSizePolicy(sizePolicy)
        self.clipLength.setMinimumSize(QtCore.QSize(50, 0))
        self.clipLength.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clipLength.setBaseSize(QtCore.QSize(50, 0))
        self.clipLength.setObjectName("clipLength")
        self.gridLayout_2.addWidget(self.clipLength, 0, 1, 1, 1)
        self.minuteLabel = QtWidgets.QLabel(self.clipSettingsBox)
        self.minuteLabel.setObjectName("minuteLabel")
        self.gridLayout_2.addWidget(self.minuteLabel, 0, 2, 1, 1)
        self.segLengthLabel = QtWidgets.QLabel(self.clipSettingsBox)
        self.segLengthLabel.setObjectName("segLengthLabel")
        self.gridLayout_2.addWidget(self.segLengthLabel, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.clipSettingsBox, 2, 0, 1, 3)
        self.videoSettingsBox = QtWidgets.QGroupBox(self)
        self.videoSettingsBox.setObjectName("videoSettingsBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.videoSettingsBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.colorLabel = QtWidgets.QLabel(self.videoSettingsBox)
        self.colorLabel.setObjectName("colorLabel")
        self.gridLayout_3.addWidget(self.colorLabel, 3, 0, 1, 1)
        self.isoLabel = QtWidgets.QLabel(self.videoSettingsBox)
        self.isoLabel.setObjectName("isoLabel")
        self.gridLayout_3.addWidget(self.isoLabel, 1, 0, 1, 1)
        self.compressionSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.compressionSlider.setObjectName("compressionSlider")
        self.compressionSlider.setValue(1)
        self.compressionSlider.setMinimum(1)
        self.compressionSlider.setMaximum(10)
        self.gridLayout_3.addWidget(self.compressionSlider, 2, 1, 1, 1)
        self.colorCombo = QtWidgets.QCheckBox(self.videoSettingsBox)
        self.colorCombo.setObjectName("colorCombo")
        self.gridLayout_3.addWidget(self.colorCombo, 3, 1, 1, 1)
        self.frameSec = QtWidgets.QSpinBox(self.videoSettingsBox)
        self.frameSec.setObjectName("frameSec")
        self.gridLayout_3.addWidget(self.frameSec, 0, 1, 1, 1)
        self.gain = QtWidgets.QSpinBox(self.videoSettingsBox)
        self.gain.setObjectName("gain")
        self.gridLayout_3.addWidget(self.gain, 6, 1, 1, 1)
        self.compressionLabel = QtWidgets.QLabel(self.videoSettingsBox)
        self.compressionLabel.setObjectName("compressionLabel")
        self.gridLayout_3.addWidget(self.compressionLabel, 2, 0, 1, 1)
        self.isoCombo = QtWidgets.QComboBox(self.videoSettingsBox)
        self.isoCombo.setObjectName("isoCombo")
        self.isoCombo.addItem("")
        self.isoCombo.addItem("")
        self.isoCombo.addItem("")
        self.isoCombo.addItem("")
        self.isoCombo.addItem("")
        self.isoCombo.addItem("")
        self.gridLayout_3.addWidget(self.isoCombo, 1, 1, 1, 1)
        self.vflipCheck = QtWidgets.QCheckBox(self.videoSettingsBox)
        self.vflipCheck.setObjectName("vflipCheck")
        self.gridLayout_3.addWidget(self.vflipCheck, 4, 0, 1, 1)
        self.frameSecLabel = QtWidgets.QLabel(self.videoSettingsBox)
        self.frameSecLabel.setObjectName("frameSecLabel")
        self.gridLayout_3.addWidget(self.frameSecLabel, 0, 0, 1, 1)
        self.autogainCheck = QtWidgets.QCheckBox(self.videoSettingsBox)
        self.autogainCheck.setObjectName("autogainCheck")
        self.gridLayout_3.addWidget(self.autogainCheck, 5, 0, 1, 1)
        self.gainLabel = QtWidgets.QLabel(self.videoSettingsBox)
        self.gainLabel.setObjectName("gainLabel")
        self.gridLayout_3.addWidget(self.gainLabel, 6, 0, 1, 1)
        self.gridLayout_4.addWidget(self.videoSettingsBox, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 4, 1, 1, 1)
        self.retranslateUi()
        self.buttons = {"names": self.namesButton, "okay": self.okayButton, "default": self.defaultButton,
                        "iso": self.isoCombo, "compression": self.compressionSlider, "color": self.colorCombo,
                        "vflip": self.vflipCheck, "autogain": self.autogainCheck}
        self.text = {"clip len": self.clipLength, "fps": self.frameSec, "gain": self.gain,
                     "compressionLabel": self.compressionLabel}

    def retranslateUi(self):
        """Sets the text for all the UI elements.

        Supposedly used as a hook for QT to translate things while running (and
        is currently called at the end of init). We don't have localization
        (yet?) so we just run it once.
        """
        self.setWindowTitle("Settings")
        self.namesButton.setText("Camera Names")
        self.okayButton.setText("OK")
        self.defaultButton.setText("Default")
        self.clipSettingsBox.setTitle("Clip Settings")
        self.clipLength.setValue(2)
        self.minuteLabel.setText("minutes")
        self.segLengthLabel.setText("Video segment length:")
        self.videoSettingsBox.setTitle("Video Settings")
        self.colorLabel.setText("Color")
        self.isoLabel.setText("ISO:")
        self.frameSec.setValue(30)
        self.compressionLabel.setText("Compression: 1x")
        self.isoCombo.setItemText(0, "0")
        self.isoCombo.setItemText(1, "100")
        self.isoCombo.setItemText(2, "200")
        self.isoCombo.setItemText(3, "400")
        self.isoCombo.setItemText(4, "800")
        self.isoCombo.setItemText(5, "1600")
        self.vflipCheck.setText("V-Flip")
        self.frameSecLabel.setText("Frames per second:")
        self.autogainCheck.setText("Auto-Gain")
        self.gainLabel.setText("Gain:")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = SettingsWindow()
    window.show()
    sys.exit(app.exec_())
